---
- name: Install {{ cda_package }} dependencies
  apt:
    name: "{{ cda_dependencies_packages }}"
    state: present
  tags:
    - install

- name: Download {{ cda_package }}
  get_url:
    url: "{{ cda_package_url }}"
    dest: "/{{ cda_temp_path }}/{{ cda_package }}"
    timeout: "{{ cda_global_downloads_timeout }}"
    mode: 0755
  tags:
    - download
    - install

- name: Install {{ cda_package }}
  command: "/{{ cda_temp_path }}/{{ cda_package }} auto"
  changed_when: false
  tags:
    - install
