---
# references
# https://docs.aws.amazon.com/es_es/codedeploy/latest/userguide/welcome.html

- name: Get amazon linux version from "uname" command
  shell: >
    awk -v FS="recipe_name=" 'NF>1{print $2}' /etc/image-id | tr -d '"' | awk '{print $1}'
  ignore_errors: true
  register: amazon_linux_recipe_name_result
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon'
  changed_when: false

# Define facts to manage amazon linux version in a easy way
- name: Set fact "amazon_linux_distribution_version" for amazon linux 1
  set_fact:
    amazon_linux_distribution_version: 1
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    amazon_linux_recipe_name_result.stdout == 'amzn'

- name: Set fact "amazon_linux_distribution_version" for amazon linux 2
  set_fact:
    amazon_linux_distribution_version: 2
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    amazon_linux_recipe_name_result.stdout == 'amzn2'

# Define facts for AWS Region
- name: Try to get region from ec2 metadata
  uri:
    url: "{{ cda_aws_metadata_document }}"
    return_content: true
    timeout: 2
  register: aws_metadata_document
  failed_when: false

- name: Set facts for AWS Region and Location when metadata works
  set_fact:
    cda_aws_region_metadata: "{{ aws_metadata_document.json.region }}"
    cda_is_aws_instance__dot_not_use_it: true
  when: aws_metadata_document.status == 200

# Include vars
- name: Include variables for RHEL/Centos/Amazon Linux distribution
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family|lower }}.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat' or
      ansible_distribution == 'Amazon'
    )
  tags:
    - include-redhat-vars

- name: Include variables for Debian
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family|lower }}.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Debian'
  tags:
    - include-debian-vars

- name: Include variables for Ubuntu
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Ubuntu'
  tags:
    - include-ubuntu-vars

# Installation tasks
- name: Include tasks for installation on RedHat/CentOS/Amazon distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat' or
      ansible_distribution == 'Amazon'
    )
  tags:
    - include-redhat-task

- name: Include tasks for installation on Debian/Ubuntu distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and (
    ansible_distribution == 'Debian' or
    ansible_distribution == 'Ubuntu'
    )
  tags:
    - include-debian-task

- name: Configure {{ cda_package }} RedHat/CentOS/Amazon distribution
  include_tasks: "configure-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'RedHat'
  tags:
    - configure

- name: Configure {{ cda_package }} Debian/Ubuntu distribution
  include_tasks: "configure-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and not (
      ansible_distribution == 'Ubuntu' and 
      ansible_distribution_major_version == '14'
    )
  tags:
    - configure

- name: Configure {{ cda_package }} on Ubuntu 14 Linux distribution
  include_tasks: "configure-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Ubuntu' and 
    ansible_distribution_major_version == '14'
  tags:
    - configure-ubuntu-14